### ISSUE TITLE
Not working, even for provided examples

### ISSUE THREAD

**Issue by johntfoster** [prabhuramachandran/tex2ipy#1]
When attempting to run `tex2ipy`, even for the examples provided, I get the following traceback

````
Traceback (most recent call last):
  File "/Users/john/miniconda3/envs/rise/bin/tex2ipy", line 11, in <module>
    sys.exit(main())
  File "/Users/john/miniconda3/envs/rise/lib/python3.6/site-packages/tex2ipy/cli.py", line 73, in main
    nbformat.write(nb, f)
  File "/Users/john/miniconda3/envs/rise/lib/python3.6/site-packages/nbformat/__init__.py", line 166, in write
    s = writes(nb, version, **kwargs)
  File "/Users/john/miniconda3/envs/rise/lib/python3.6/site-packages/nbformat/__init__.py", line 111, in writes
    return versions[version].writes_json(nb, **kwargs)
  File "/Users/john/miniconda3/envs/rise/lib/python3.6/site-packages/nbformat/v4/nbjson.py", line 56, in writes
    nb = split_lines(nb)
  File "/Users/john/miniconda3/envs/rise/lib/python3.6/site-packages/nbformat/v4/rwbase.py", line 81, in split_lines
    if cell.cell_type == 'code':
AttributeError: 'dict' object has no attribute 'cell_type'
````

This happens with both `pip` installs and manual.

**Comment by prabhuramachandran** [comment]
@johntfoster -- thanks for bringing this up.  I'll fix it by tonight. nbformat 4.4 changed something that breaks this and I've fixed it in http://github.com/prabhuramachandran/ipyaml so will apply that here as well.

**Comment by prabhuramachandran** [comment]
I just pushed some fixes to address this, the tests pass for me but are broken on travis, I'll investigate but I suspect this fix should address this issue.

**Comment by prabhuramachandran** [comment]
Looks like the latest version of TexSoup has changed many things and I'll need to update tex2ipy to fix the test failures, I'll need more time for this so will look at this later tonight.

**Comment by prabhuramachandran** [comment]
I've fixed the code and tests to work with the latest version of TexSoup.  Am closing this issue, please open a new issue or reopen this if you run into problems.

**Comment by johntfoster** [comment]
Thanks, great work.  I'll install from the git repo, but don't forget to
push the changes to pypi when you get a chance.

**Comment by prabhuramachandran** [comment]
Thanks! I've pushed new releases of tex2ipy and ipyaml on pypi.
